apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: app
  name: app
  namespace: devops-poc
spec:
  replicas: 2
  selector:
    matchLabels:
      run: app
  template:
    metadata:
      labels:
        run: app
    spec:
      containers:
      - name: app
        image: secretlyelvis/helloworldwc
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: app
  name: app
  namespace: devops-poc
  annotations:
    haproxy.org/check: "enabled"
    haproxy.org/forwarded-for: "enabled"
    haproxy.org/load-balance: "roundrobin"
spec:
  selector:
    run: app
  ports:
  - name: port-1
    port: 80
    protocol: TCP
    targetPort: 8080

---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: web-ingress
  namespace: devops-poc
spec:
  rules:
  - http:
      paths:
      - path: /test
        backend:
          serviceName: app
          servicePort: 80


#spec:
#  rules:
#  - host: devops-poc.com
#    http:
#      paths:
#      - path: /test
#        backend:
#          serviceName: app
#          servicePort: 80