apiVersion: v1
kind: Namespace
metadata:
  name: test-app
  
---
#### TEST APP 1
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: psql-client
  name: psql-client
  namespace: test-app
spec:
  replicas: 1
  selector:
    matchLabels:
      run: psql-client
  template:
    metadata:
      labels:
        run: psql-client
    spec:
      containers:
      - name: psql-client
        image: secretlyelvis/psql-client:latest