apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: nexus-prd 
  labels:
    app: nexus-prd 
  name: nexus-prd 
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: nexus-prd 
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nexus-prd 
    spec:
      containers:
      - name: nexus-prd 
        image: quay.io/travelaudience/docker-nexus:3.27.0
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
          protocol: TCP
        - containerPort: 8081
          protocol: TCP
        - containerPort: 8082
          protocol: TCP
        resources:
          limits:
            cpu: "4"
            memory: 2500Mi
          requests:
            cpu: 500m
            memory: 1000Mi
        volumeMounts:
        - mountPath: "nexus-data"
          name: nexus-prd-fs 
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      volumes:
        - name: nexus-prd-fs 
          persistentVolumeClaim:
            claimName: nexus-prd-pvc 
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
----
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nexus-prd 
  name: nexus-prd 
  namespace: nexus-prd 
spec:
  ports:
  - name: http
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: nexus-prd 
----
apiVersion: v1
kind: Service
metadata:
  labels:
    app: docker-reg 
  name: docker-reg 
  namespace: nexus-prd 
spec:
  ports:
  - name: docker-reg 
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: nexus-prd 
----
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  namespace: nexus-prd 
  name: dockr-reg 
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/group.name: lylty-devops-poc
spec:
  rules:
  - host: lylty-images.devops-poc.com
    http:
      paths:
      - backend:
          serviceName: docker-reg 
          servicePort: 5000
----
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  namespace: nexus-prd 
  name: nexus-admin 
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/group.name: lylty-devops-poc
spec:
  rules:
  - host: lylty-nexus.example.com
    http:
      paths:
      - backend:
          serviceName: nexus-prd 
          servicePort: 8081