# PersistentVolume for Nexus Repository Manager
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nexus-prd-pv
  namespace: devops-poc 
spec:
  storageClassName: nexus-prd-pv
  capacity:
    storage: 1024Gi
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: efs.csi.aws.com
    volumeHandle: "<FS_ID>::<FSAP_ID>"
---
# Persistent Volume Claim for Nexus
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nexus-prd-pvc
  namespace: devops-poc 
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nexus-prd-pv
  volumeName: nexus-prd-pv
  resources:
    requests:
      storage: 1024Gi
    
    