# PersistentVolume for Nexus Repository Manager
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nexus-prd-pv
spec:
  storageClassName: nexus-prd-pv
  capacity:
    storage: 1024Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: <EFS_URL>
    path: "/nexus_prd"