name: nexus
version: 0.0.2
description: Sonatype Nexus Repository Manager 3.
keywords:
  - Maven Repository
  - NPM Repository
  - Nuget Repository
home: http://www.sonatype.org/nexus/category/nexus-3/
sources:
  - https://github.com/sonatype/docker-nexus3
maintainers:
  - name: Daniel Auld
    email: daniel.auld@loyalty.co.nz
engine: gotpl
