# PersistentVolume for Jenkins Control Pod
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-dev-pv
spec:
  storageClassName: jenkins-dev-pv
  capacity:
    storage: 1024Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: <EFS_URL>
    path: "/jenkins_dev"
    
    